# This class is for parsing SBML
# IMPORTANT: This will only work for SBML that is generated by PathWhiz, as normal
# SBML does not have positional information.
# Since we assume this pathway came from PathWhiz, it will only parse correctly 
# if all the data elements are already in PathWhiz
class SbmlParser
  SPECIES = %w(Bound Compound ElementCollection NucleicAcid Protein ProteinComplex)
  REACTIONS = %w(Reaction ReactionCoupledTransport Transport Interaction SubPathway)

  def initialize()
    # Hashes to stores all the elements for this visualizations
    # Keys are the ids in the SBML
    # Values are the corresponding element in the database
    @elements = {}
    @elements[:biological_states] = {}

    @elements[:bounds] = {}
    @elements[:compounds] = {}
    @elements[:element_collections] = {}
    @elements[:nucleic_acids] = {}
    @elements[:proteins] = {}
    @elements[:protein_complexes] = {}

    @elements[:reactions] = {}
    @elements[:reaction_coupled_transports] = {}
    @elements[:transports] = {}
    @elements[:interactions] = {}
    @elements[:sub_pathways] = {}

    # Keeps track of which visual elements we have already added 
    # so we don't add duplicates
    @locations = {}
    @locations[:compound_locations] = {}
    @locations[:element_collection_locations] = {}
    @locations[:nucleic_acid_locations] = {}
    @locations[:protein_locations] = {}

    @result = {}
    @result[:errors] = {}
  end

  # Parse the file and create the pathway
  # If overwrite, then replace the existing pathway with this one, else create
  # a new pathway
  def parse(file, user_id = 11, overwrite = false)
    doc = Nokogiri::XML(file) do |config|
      config.strict.noblanks
    end

    # Check that all the compartment and species in the SBML are already
    # in the database
    validate_and_store(doc)

    if @result[:errors].present?
      return @result
    end

    if (identifier = doc.at_css("model > annotation bqbiol|is rdf|li[rdf|resource^='urn:miriam:pathwhiz']")).present? &&
      (spv = SuperPathwayVisualization.find_by_pw_id(identifier.attr("rdf:resource").gsub!(/[^:]+:/, ""))).present? &&
      (pathway = spv.named_for).present?

      if overwrite
        # Replace the existing pathway visualization with this one

      else
        dimensions = doc.at_css("model > annotation > pathwhiz|dimensions")
        if dimensions
          width = dimensions.attr("pathwhiz:width").to_i
          height = dimensions.attr("pathwhiz:height").to_i
        else
          add_error(:pathway, "Dimensions missing")
          return @result
        end

        # Create a new pathway
        new_pathway = Pathway.create({name: pathway.name + " " + Time.now.to_i.to_s, 
                             description: pathway.description, 
                             subject: pathway.subject, 
                             user_id: pathway.user_id,
                             species_id: pathway.species_id
                             })
        new_pv = PathwayVisualization.create({pathway_id: new_pathway.id, user_id: user_id, height: height, width: width})
        new_spv = SuperPathwayVisualization.create({named_for_id: new_pathway.id, named_for_type: "Pathway", user_id: user_id})
        new_pvc = PathwayVisualizationContext.create({pathway_visualization_id: new_pv.id, super_pathway_visualization_id: new_spv.id, position: "Center"})
        new_pathway.update_attribute(:primary_spv, new_spv.id)
      end

      doc.css("listOfReactions reaction").each do |reaction|
        sbml_id = reaction.attr("id")
        reaction_id, reaction_type = get_identifiers(reaction, "reaction")
        biological_state = @elements[:biological_states][reaction.attr("compartment")]
        stored_reaction = @elements[(reaction_type.underscore.pluralize).to_sym][sbml_id]

        # Create the reaction visualization
        new_rv = "#{reaction_type.camelize}Visualization".constantize.new()
        new_rv.pathway_visualization = new_pv
        if new_rv.has_attribute?(:biological_state_id)
          new_rv.biological_state = biological_state
        end
        new_rv.send("#{reaction_type.underscore}=", stored_reaction)

        # For subpathways, if the subpathway is just a reference
        if (reaction_location = reaction.at_css("> annotation pathwhiz|location > pathwhiz|location_element")).present?
          new_rv.visualization_template_id = reaction_location.attr("pathwhiz:visualization_template_id").try(:to_i)
          new_rv.hidden = to_boolean(reaction_location.attr("pathwhiz:hidden"))
          new_rv.zindex = reaction_location.attr("pathwhiz:zindex").try(:to_i)
          new_rv.x = reaction_location.attr("pathwhiz:x").try(:to_i)
          new_rv.y = reaction_location.attr("pathwhiz:y").try(:to_i)
        end

        # Do all reactants i.e. left elements
        reaction.css("listOfReactants speciesReference").each do |reactant|

          location = reactant.at_css("pathwhiz|location")
          location_type = location.attr("pathwhiz:location_type")

          # Create the reaction visualization association
          new_ra = "#{reaction_type.camelize}#{location_type.camelize}Visualization".constantize.new()
          new_ra.send("#{reaction_type}_visualization=", new_rv)
          new_ra.side = "Left"

          # Create each location element
          location.css("> pathwhiz|location_element").each do |element|
            # Make the element
            new_element = make_location(element, new_pv)
            # Add the element to the association
            new_ra.send("#{new_element.class.to_s.underscore}=", new_element)

            # Add the association to the visualization

            new_rv.send("#{reaction_type}_#{location_type}_visualizations=", 
              new_rv.send("#{reaction_type}_#{location_type}_visualizations") << new_ra)
          end

        end

        # Do all products i.e. right elements
        reaction.css("listOfProducts speciesReference").each do |reactant|

          location = reactant.at_css("pathwhiz|location")
          location_type = location.attr("pathwhiz:location_type")

          # Create the reaction visualization association
          new_ra = "#{reaction_type.camelize}#{location_type.camelize}Visualization".constantize.new()
          new_ra.send("#{reaction_type}_visualization=", new_rv)
          new_ra.side = "Right"

          # Create each location element
          location.css("> pathwhiz|location_element").each do |element|
            # Make the element
            new_element = make_location(element, new_pv)
            # Add the element to the association
            new_ra.send("#{new_element.class.to_s.underscore}=", new_element)
          end

          # Add the association to the visualization
          new_rv.send("#{reaction_type}_#{location_type}_visualizations=", 
            new_rv.send("#{reaction_type}_#{location_type}_visualizations") << new_ra)

        end

        # Do all products i.e. right elements
        reaction.css("listOfModifiers modifierSpeciesReference").each do |reactant|

          location = reactant.at_css("pathwhiz|location")
          location_type = location.attr("pathwhiz:location_type")

          # Create the reaction enzyme/transporter association
          if reaction_type =~ /^reaction/
            new_ra = "#{reaction_type.camelize}EnzymeVisualization".constantize.new()
          elsif reaction_type =~ /^transport/
            new_ra = TransportTransporterVisualization.new()
          else
            next
          end

          new_ra.send("#{reaction_type}_visualization=", new_rv)

          # Create each location element
          location.css("> pathwhiz|location_element").each do |element|
            # Make the element
            new_element = make_location(element, new_pv)
            # Add the element to the association
            new_ra.protein_complex_visualization = new_element
            if reaction_type =~ /^reaction/
              new_ra.send("#{reaction_type}_enzyme=", stored_reaction.get_enzyme(new_element.protein_complex.id))
            elsif reaction_type =~ /^transport/
              new_ra.transport_transporter = stored_reaction.get_enzyme(new_element.protein_complex.id)
            end
          end

          if reaction_type =~ /^reaction/
            # Add the association to the visualization
            new_rv.send("#{reaction_type}_enzyme_visualizations=", 
              new_rv.send("#{reaction_type}_enzyme_visualizations") << new_ra )
          elsif reaction_type =~ /^transport/
            # Add the association to the visualization
            new_rv.transport_transporter_visualizations << new_ra
          end

        end

        if !new_rv.save
          add_error(:process, "Error adding process #{sbml_id}")
        end

      end

      if @result[:errors].present?
        new_spv.pathway_visualization_contexts.each do |pvc|
          pvc.context.try(:destroy)
          pvc.pathway_visualization.pathway.try(:destroy)
          pvc.pathway_visualization.try(:destroy)
        end
      else
        @result[:success] = true
        @result[:pathway_id] = new_pathway.id
      end

      return @result

    else
      add_error(:pathway, "Reference pathway not found")
      return @result
    end

  end

  # Checks all the compartments, species and reactions in the SBML and makes sure
  # they are all already in PathWhiz with matching ids and names
  def validate_and_store(doc)
    doc.css("listOfCompartments compartment").each do |compartment|
      name = compartment.attr("name")
      sbml_id = compartment.attr("id")
      compartment_id, compartment_type = get_identifiers(compartment, "compartment")
      if compartment_id.present? && compartment_type.present? && 
        (bs = compartment_type.camelize.constantize.where(id: compartment_id).take).present? && 
        bs.name == name

        @elements[:biological_states][sbml_id] = bs
      else
        if @result[:errors][:compartments].nil?
          @result[:errors][:compartments] = []
        end
        add_error(:compartments, "#{sbml_id} is not a valid compartment from PathWhiz")
      end
    end

    doc.css("listOfSpecies species").each do |species|
      name = species.attr("name")
      sbml_id = species.attr("id")
      compartment_id = species.attr("compartment")
      species_id, species_type = get_identifiers(species, "species")
      if species_id.present? && species_type.present? && 
        SPECIES.include?(species_type.camelize) && 
        (s = species_type.camelize.constantize.where(id: species_id).take).present? && 
        s.name == name

        @elements[(species_type.underscore.pluralize).to_sym][sbml_id] = 
          [s, @elements[:biological_states][compartment_id]]
      else
        add_error(:species, "#{sbml_id} is not a valid species from PathWhiz")
      end
    end

    doc.css("listOfReactions reaction").each do |reaction|
      name = reaction.attr("name")
      sbml_id = reaction.attr("id")
      compartment_id = reaction.attr("compartment")
      # For reactions the SBML id is the reaction VISUALIZATION id, not the data id
      reaction_id, reaction_type = get_identifiers(reaction, "reaction")
      if reaction_id.present? && reaction_type.present? && 
        REACTIONS.include?(reaction_type.camelize) && 
        (r = reaction_type.camelize.constantize.where(id: reaction_id).take).present? && 
        r.name == name

        @elements[(reaction_type.underscore.pluralize).to_sym][sbml_id] = r
      else
        add_error(:reactions, "#{sbml_id} is not a valid reaction from PathWhiz")
      end
    end
  end

  def get_identifiers(element, category)
    id = (annotation = element.at_css("annotation pathwhiz|#{category}")).present? ? 
        annotation.attr("pathwhiz:#{category}_id") : ""
    type = (annotation = element.at_css("annotation pathwhiz|#{category}")).present? ? 
        annotation.attr("pathwhiz:#{category}_type") : ""

    return [id, type]
  end

  def make_location(element, pathway_visualization)
    element_type = element.attr("pathwhiz:element_type")
    sbml_id = element.attr("pathwhiz:element_id")
    location_id = element.attr("pathwhiz:location_id")
    data_name = element_type.underscore.gsub(/_[^_]+$/, "")

    if @locations[element_type.pluralize.to_sym].present? && (saved_location = @locations[element_type.pluralize.to_sym][location_id]).present?
      return saved_location
    else

      # Create visual element
      new_l = element_type.camelize.constantize.new()
      new_l.pathway_visualization = pathway_visualization

      if element_type != "edge"
        # Get reference data element
        stored_element, element_compartment = @elements[(data_name.pluralize).to_sym][sbml_id]
        new_l.send("#{stored_element.class.to_s.underscore}=", stored_element)
        if element_compartment.present?
          new_l.biological_state = element_compartment
        end
      end

      # For bound and protein complex visualizations,
      # their elements have the visualization details, not themselves
      if element_type =~ /_visualization$/
        # Create associated elements for bound and protein_complex visualizations
        element.css("> pathwhiz|location_element").each do |element|
          # Make the element
          new_element = make_location(element, pathway_visualization)
          element_name = new_element.class.to_s.underscore.gsub(/_[^_]+$/, "")

          # Make the location association
          new_la = "#{data_name.camelize}#{element_name.camelize}Visualization".constantize.new()
          new_la.send("#{element_type}=", new_l)

          # Add the element to the association
          new_la.send("#{new_element.class.to_s.underscore}=", new_element)

          # Special case, protein_complex_compounds need a compound_type
          if new_la.class == ProteinComplexCompoundVisualization
            new_la.compound_type = element.attr("pathwhiz:compound_type")
          end

          # Add the other associated elements (i.e. edges)
          element.css("> pathwhiz|location_element").each do |element|
            # Make the element
            new_element = make_location(element, pathway_visualization)
            # Add the element to the association
            new_la.send("#{new_element.class.to_s.underscore}=", new_element)
          end

          # Add the association to the visualization
          new_l.send("#{data_name}_#{element_name}_visualizations=", 
            new_l.send("#{data_name}_#{element_name}_visualizations") << new_la)
        end
      else
        new_l.visualization_template_id = element.attr("pathwhiz:visualization_template_id").try(:to_i)
        new_l.hidden = to_boolean(element.attr("pathwhiz:hidden"))
        new_l.zindex = element.attr("pathwhiz:zindex").try(:to_i)
        if element_type == "edge"
          new_l.path = element.attr("pathwhiz:path")
          new_l.options = element.attr("pathwhiz:options")
        else
          new_l.x = element.attr("pathwhiz:x").try(:to_i)
          new_l.y = element.attr("pathwhiz:y").try(:to_i)
        end
      end

      if !new_l.save
        add_error(:location, "Error adding location for #{sbml_id}")
      else
        if @locations[element_type.pluralize.to_sym].present?
          @locations[element_type.pluralize.to_sym][location_id] = new_l
        end
      end

      return new_l
    end
  end

  def to_boolean(val)
    if val == "true"
      1
    else
      0
    end
  end

  def add_error(type, message)
    if @result[:errors][type].blank?
      @result[:errors][type] = []
    end

    @result[:errors][type] << message

  end

end